[build]
baseImage = "python:3.11"
providers = ["node=18"]

[phases.setup]
cmds = [
    "apt-get update && apt-get install -y libsndfile1",
    "pip install -r back/requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "uvicorn back.main:app --host 0.0.0.0 --port $PORT"