[build]
providers = ["python=3.11", "node=18"]

[phases.setup]
cmds = [
    # 1. Instalar dependencias del sistema
    "apt-get update",
    "apt-get install -y python3 python3-venv python3-dev nodejs npm build-essential libsndfile1 ffmpeg",
    
    # 2. Crear virtual environment e instalar dependencias en UN SOLO COMANDO
    "python3 -m venv /app/venv && . /app/venv/bin/activate && pip install --upgrade pip && pip install -r back/requirements.txt",
    
    # 3. Configurar Node.js
    "cd frontend && npm install",
    
    # 4. Build del frontend
    "cd frontend && npm run build"
]

[start]
cmd = ". /app/venv/bin/activate && uvicorn back.main:app --host 0.0.0.0 --port $PORT"