[build]
providers = ["python=3.11", "node=18"]

# TODO en una sola fase para garantizar el orden correcto
[phases.setup]
cmds = [
    # 1. Instalar dependencias del sistema
    "apt-get update",
    "apt-get install -y python3 python3-pip python3-venv python3-dev nodejs npm build-essential libsndfile1 ffmpeg",
    
    # 2. Configurar Python
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r back/requirements.txt",
    
    # 3. Configurar Node.js
    "cd frontend && npm install",
    
    # 4. Build del frontend
    "cd frontend && npm run build"
]

[start]
cmd = "python3 -m uvicorn back.main:app --host 0.0.0.0 --port $PORT"