[phases.setup]
cmds = [
  "cd back && pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd back && uvicorn main:app --host 0.0.0.0 --port $PORT"