[build]
providers = ["python=3.11", "node=18"]

[phases.setup]
cmds = [
    # 1. Instalar dependencias del sistema
    "apt-get update",
    "apt-get install -y build-essential libsndfile1 ffmpeg",

    # 2. Instalar dependencias del backend (ya tienes pip en la imagen)
    "pip install --upgrade pip",
    "pip install -r back/requirements.txt",

    # 3. Configurar Node.js
    "cd frontend && npm install",

    # 4. Build del frontend
    "cd frontend && npm run build"
]

[start]
cmd = "uvicorn back.main:app --host 0.0.0.0 --port $PORT"
